### ISSUE TITLE
Loadmore right after Pull to refresh

### ISSUE THREAD

**Issue by eneim** [ogaclejapan/Qiitanium#1]
リストをpullした直後にloadmoreすると、アイテムが複製（duplicated?!）される場合があります。おそらく、ロードする時、アイテムリストをsynchronizeしなかったわけ？

あと、僕自分もQiitaクライアントを作ってますが、markdownの表示がうまく進めないためで止まってしまいます。Ogacleさんの解決方法(jsoup + html)は本当にすごい（simple, yet powerful/beautiful）ので、アイデアを借りて自分のものを完成させていただきたいと思います。

**Comment by ogaclejapan** [comment]
Thank you for reporting the problem. 

現在、デザインを大幅に変更したバージョン0.2を開発中です。
このリリースタイミングと合わせて問題箇所の実装変更を検討してみます :P

そうですね、Markdownの扱いは難しいですよね。
eneimさんのQiitaクライアントが完成したら、ぜひ教えてくださいね :)

**Comment by ogaclejapan** [comment]
ライブラリの実装bugでPull to refreshしたときにclearメソッドが効いてなかったようです。
https://github.com/ogaclejapan/RxBinding/issues/1

v0.2では修正版を使っているのでこの問題は解消されています。
