### ISSUE TITLE
Can not launch on Marshmallow

### ISSUE THREAD

**Issue by hotchemi** [ogaclejapan/Qiitanium#5]
I'm not sure the reason but you might use reflection or something like that(like ActiveAndroid).
Any idea?

**Comment by ogaclejapan** [comment]
Hi, @hotchemi 
Thank you for reporting

I forget release... : P
Maybe, I think this problem. #4

**Comment by hotchemi** [comment]
Gotcha! Thx:-)

**Comment by ogaclejapan** [comment]
0.2.1 has released :shipit:

**Comment by hotchemi** [comment]
:+1:
